language: java
jdk:
- oraclejdk8
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- '[ "$TRAVIS_PULL_REQUEST" = "true" ] && git checkout HEAD^2 && echo "OCTOPULL_SHA=$(git rev-parse HEAD)"; true'
script:
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn test -Ptravis -B; else true; fi;'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn test -B; else true; fi;'
notifications:
  webhooks:
  - http://octopull.rmhartog.me/api/travis/webhook
after_script:
- echo "== CHECKSTYLE_RESULT ==" && cat "target/checkstyle-result.xml" && echo "== END_CHECKSTYLE_RESULT =="
- echo "== PMD_RESULT ==" && cat "target/pmd.xml" && echo "== END_PMD_RESULT =="
- echo "== FINDBUGS_RESULT ==" && cat "target/findbugsXml.xml" && echo "== END_FINDBUGS_RESULT =="
