language: java
jdk:
  - oraclejdk8
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "[ \"$BUILD_PR_BRANCH\" = \"true\" ] && git checkout HEAD^2 && echo \"OCTOPULL_SHA=$(git rev-parse HEAD)\"; true"
script: mvn test -B
notifications:
  webhooks:
    - http://octopull.rmhartog.me/api/travis/webhook
env:
  - BUILD_PR_BRANCH=true
  - BUILD_PR_BRANCH=false
matrix:
  include:
    - env: BUILD_PR_BRANCH=true
      script: mvn site -B
after_script:
  - echo "== CHECKSTYLE_RESULT ==" && cat "target/checkstyle-result.xml" && echo "== END_CHECKSTYLE_RESULT =="
  - echo "== PMD_RESULT ==" && cat "target/pmd.xml" && echo "== END_PMD_RESULT =="
  - echo "== FINDBUGS_RESULT ==" && cat "target/findbugsXml.xml" && echo "== END_FINDBUGS_RESULT =="
